### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by dutchsing009** [freds0/katube#1]
hey how are you , Openai new speech to text model has been released it is called Whisper https://github.com/openai/whisper   
you can use it for transcription then use aeneas to do the rest , you might also make that for https://github.com/freds0/youtube_diarization or add youtube_diarization to here and make it a one full repo 

these were just some ideas , 

Thank you :)

**Comment by freds0** [comment]
I have only seen your message now! Thanks for the sugestion!
